# Generated by Django 5.2.8 on 2026-07-24 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0004_organisation_anon_reporting_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier used in code, e.g. 'custom_report_forms'", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('beta', 'Beta'), ('stable', 'Stable')], default='beta', max_length=10)),
                ('is_enrollable', models.BooleanField(default=True, help_text='If False, this feature is hidden from the beta enrollment UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgBetaEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_beta_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(blank=True, help_text='Leave empty to enroll in ALL beta features.', related_name='org_enrollments', to='beta.betafeature')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beta_enrollment', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='UserBetaEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, help_text='Leave empty to enroll in ALL beta features.', related_name='user_enrollments', to='beta.betafeature')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beta_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
