# Generated by Django 5.2.8 on 2026-07-24 10:45

import django.db.models.deletion
import restapi.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_reportformconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(help_text='User-given alias for this key', max_length=100)),
                ('public_key', models.CharField(db_index=True, default=restapi.models.generate_public_key, max_length=40, unique=True)),
                ('hashed_secret', models.CharField(max_length=256)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Key auto-expires after this datetime.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiKeyScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('reports', 'Reports'), ('comments', 'Comments'), ('projects', 'Projects')], max_length=30)),
                ('action', models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('delete', 'Delete')], max_length=10)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='restapi.apikey')),
            ],
            options={
                'unique_together': {('api_key', 'resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='restapi.apikey')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['api_key', 'requested_at'], name='restapi_api_api_key_1e44bf_idx'), models.Index(fields=['api_key', 'status_code'], name='restapi_api_api_key_a12190_idx')],
            },
        ),
    ]
