# Generated by Django 5.2.8 on 2026-02-07 15:40

from django.db import migrations, models
from uuid6 import uuid7


def backfill_project_uuids(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.filter(uuid__isnull=True):
        project.uuid = uuid7()
        project.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_collaborators"),
    ]

    operations = [
        # 1️⃣ Add uuid field safely (nullable, no default)
        migrations.AddField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),

        # 2️⃣ Backfill UUIDs row-by-row
        migrations.RunPython(backfill_project_uuids),
    ]