# Generated by Django 5.2.8 on 2026-02-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_organisation_members'),
        ('projects', '0005_alter_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.organisation'),
        ),
    ]
