# Generated by Django 5.2.8 on 2026-07-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_project_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('org', 'Organization Members Only'), ('private', 'Private (Owner & Collaborators Only)')], default='public', max_length=20),
        ),
    ]
