# Generated by Django 5.2.8 on 2026-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_attachment_types',
            field=models.CharField(default='.jpg,.jpeg,.png,.pdf,.doc,.docx,.xls,.xlsx,.zip,.txt', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='max_attachments',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
