# Generated by Django 5.2.8 on 2026-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='anon_attachments_enabled',
            field=models.BooleanField(default=False, help_text='Allow anonymous reporters to attach files. Disabled by default to prevent abuse.'),
        ),
        migrations.AddField(
            model_name='project',
            name='anon_reporting_enabled',
            field=models.BooleanField(default=True, help_text='Allow anonymous (unauthenticated) users to submit reports via the public link.'),
        ),
        migrations.AddField(
            model_name='project',
            name='public_reporting_enabled',
            field=models.BooleanField(default=True, help_text='Allow this project to receive reports via its public reporting link.'),
        ),
    ]
