# Generated by Django 5.2.8 on 2026-07-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_anon_attachments_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, help_text='JSON configuration for the report submission form.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_config', to='projects.project')),
            ],
        ),
    ]
