# Generated by Django 5.2.8 on 2026-07-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info (Blue)'), ('warning', 'Warning (Yellow)'), ('critical', 'Critical (Red)'), ('success', 'Success (Green)')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this announcement is visible to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Automatically stop showing after this date/time.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
