# Generated by Django 5.2.8 on 2026-07-14 12:57

import django.db.models.deletion
import public_portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_project_anon_attachments_enabled_and_more'),
        ('reports', '0009_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReportingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=public_portal.models.generate_token, max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='If False, visiting this link shows a disabled page.')),
                ('allow_anonymous', models.BooleanField(default=True, help_text='Per-link toggle: allow unauthenticated users to submit via this link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_link', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AnonSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anon_submission_record', to='reports.report')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anon_submissions', to='public_portal.publicreportinglink')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
