# Generated by Django 5.2.8 on 2026-07-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0001_initial'),
        ('public_portal', '0002_create_anon_user'),
    ]

    operations = [
    ]
