# Generated by Django 5.2.8 on 2026-07-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_reportformconfig'),
        ('public_portal', '0003_merge_0001_initial_0002_create_anon_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6366f1', max_length=20)),
                ('background_color', models.CharField(default='#0f0f1a', max_length=20)),
                ('card_background', models.CharField(default='#1a1a2e', max_length=20)),
                ('text_color', models.CharField(default='#e2e8f0', max_length=20)),
                ('accent_color', models.CharField(default='#818cf8', max_length=20)),
                ('font_family', models.CharField(default='Inter', help_text='Google Font name or CSS font stack.', max_length=100)),
                ('border_radius', models.CharField(default='12px', max_length=10)),
                ('custom_css', models.TextField(blank=True, default='', help_text='Arbitrary CSS injected into the portal page. Server-sanitized and scoped to #portal-wrapper. Dangerous directives (script, javascript:, expression(), external @import) are stripped.')),
                ('custom_logo_url', models.URLField(blank=True, help_text='URL to a logo image displayed on the portal.', null=True)),
                ('custom_heading', models.CharField(blank=True, help_text='Custom heading text shown on the portal form.', max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_theme', to='projects.project')),
            ],
        ),
    ]
