# Generated by Django 5.2.8 on 2026-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0004_portaltheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaltheme',
            name='background_color',
            field=models.CharField(default='#f8f6fa', max_length=20),
        ),
        migrations.AlterField(
            model_name='portaltheme',
            name='border_radius',
            field=models.CharField(choices=[('0px', '0px (Sharp)'), ('4px', '4px (Subtle)'), ('8px', '8px (Normal)'), ('12px', '12px (Rounded)'), ('20px', '20px (Extra rounded)')], default='12px', max_length=10),
        ),
        migrations.AlterField(
            model_name='portaltheme',
            name='card_background',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='portaltheme',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Arbitrary CSS injected into the portal page. Server-sanitized and scoped to #portal-wrapper. Parsed and filtered against a property allowlist; external url(), at-rules other than @media, and unknown value functions are dropped.'),
        ),
        migrations.AlterField(
            model_name='portaltheme',
            name='font_family',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Playfair Display', 'Playfair Display')], default='Inter', help_text='Google Font name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='portaltheme',
            name='primary_color',
            field=models.CharField(default='#226ce0', max_length=20),
        ),
        migrations.AlterField(
            model_name='portaltheme',
            name='text_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
    ]
