# Generated by Django 5.2.8 on 2025-12-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('reports', '0003_report_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='commented_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
