# Generated by Django 5.2.8 on 2026-02-07 10:21

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_is_edited_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, null=True),
        ),
    ]
