# Generated by Django 5.2.8 on 2026-02-07 10:39

from django.db import migrations, models
from uuid6 import uuid7


def backfill_comment_uuids(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    for comment in Comment.objects.filter(uuid__isnull=True):
        comment.uuid = uuid7()
        comment.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0007_comment_uuid"),
    ]

    operations = [
        # 1️⃣ Ensure uuid field is nullable (safe state)
        migrations.AlterField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),

        # 2️⃣ ACTUALLY GENERATE UUIDs
        migrations.RunPython(backfill_comment_uuids),
    ]