# Generated by Django 5.2.8 on 2026-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
