# Generated by Django 5.2.8 on 2026-02-07 10:21

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, null=True),
        ),
    ]
