# Generated by Django 5.2.8 on 2026-02-07 10:37

from django.db import migrations, models
from uuid6 import uuid7


def backfill_user_uuids(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(uuid__isnull=True):
        user.uuid = uuid7()
        user.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_uuid"),
    ]

    operations = [
        # 1️⃣ Add nullable UUID field
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                null=True,
                editable=False,
                db_index=True,
            ),
        ),

        # 2️⃣ BACKFILL UUIDs (THIS WAS MISSING)
        migrations.RunPython(backfill_user_uuids),
    ]