# Generated by Django 5.2.8 on 2026-07-05 19:49

from django.db import migrations, models


def backfill_email_verified(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_email_verified=True)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(backfill_email_verified),
    ]
