# Generated by Django 5.2.8 on 2026-07-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_email_verified_user_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, help_text='If set, account is soft-deleted and will be permanently purged after this date.', null=True),
        ),
    ]
