"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'reportary.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'https://reportary.onrender.com',
]

SECURE_PROXY_SSL_HEADER = None
SESSION_COOKIE_SECURE = True      # Set to True in production (when DEBUG=False)
CSRF_COOKIE_SECURE = True         # Set to True in production (when DEBUG=False)
SESSION_COOKIE_HTTPONLY = True     # Prevent JS access to session cookie
CSRF_COOKIE_HTTPONLY = False       # Must stay False so HTMX/JS can read CSRF token
SESSION_COOKIE_SAMESITE = 'Lax'   # Mitigate CSRF on cross-site navigation
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None

# ─── Security Headers ─────────────────────────────────────────────────────────
SECURE_CONTENT_TYPE_NOSNIFF = True        # X-Content-Type-Options: nosniff
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'                  # Clickjacking protection

AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # cloudinary apps
    'cloudinary_storage',  
    'cloudinary',
    #my apps
    "rules",
    "accounts",
    "django_htmx",
    "tailwind", 
    "theme",
    "dashboard",
    "home",
    "projects",
    "components",
    "reports",
    "comments",
    "audit",
    "organisations",
    "notifications",
    "public_portal.apps.PublicPortalConfig",
    "core",
]

TAILWIND_APP_NAME = "theme"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.HtmxMessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_context',
                'core.context_processors.announcements',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

    }
}


##### PRODUCTION DATABASE SETUP ##########
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPostgres.path.replace('/', ''),
#         'USER': tmpPostgres.username,
#         'PASSWORD': tmpPostgres.password,
#         'HOST': tmpPostgres.hostname,
#         'PORT': 5432,
#         'CONN_MAX_AGE': 600,  # Persistent connections for 10 minutes
#         'CONN_HEALTH_CHECKS': True,  # Re-establish connection if dropped by remote host
#         # "OPTIONS": dict(parse_qsl(tmpPostgres.query)),
#         "OPTIONS": {
#             "sslmode": "require",
#             "keepalives": 1,
#             "keepalives_idle": 30,
#             "keepalives_interval": 10,
#             "keepalives_count": 5,
#         },
#     }
# }

# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': os.getenv('CLOUD_NAME'),
#     'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
#     'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
# }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "theme" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
TEMPLATES[0]["DIRS"] = [BASE_DIR / "core" / "templates"]

LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Email API (HTTP-based, replaces SMTP) ────────────────────────────────────
MAIL_API_KEY = os.getenv('MAIL_API', '')
MAIL_API_ENDPOINT = 'https://reportary-email-service.nagger.workers.dev/api/send'

# Contact form submissions recipient
CONTACT_EMAIL = os.getenv('CONTACT_EMAIL', 'anujkumar123.mp@gmail.com')

# ── Legacy SMTP config (kept for future reference, currently unused) ──────────
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
# EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
# EMAIL_HOST_USER = os.getenv('MAIL_ID', '')
# EMAIL_HOST_PASSWORD = os.getenv('MAIL_APP_PASSWORD', '')
# DEFAULT_FROM_EMAIL = os.getenv('MAIL_ID', 'anujkumar123.mp@gmail.com')



# ─── Public Portal Rate Limits ────────────────────────────────────────────────
# Maximum anonymous submissions per IP per link within each window.
# Override via environment variables in production.
PUBLIC_PORTAL_RATE_LIMIT_PER_HOUR = int(os.getenv('PUBLIC_PORTAL_RATE_LIMIT_PER_HOUR', 5))
PUBLIC_PORTAL_RATE_LIMIT_PER_DAY  = int(os.getenv('PUBLIC_PORTAL_RATE_LIMIT_PER_DAY', 20))
