# Generated by Django 5.2.8 on 2025-12-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='repoted_by',
            new_name='reported_by',
        ),
    ]
