# Generated by Django 5.2.8 on 2025-12-05 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('reports', '0002_rename_repoted_by_report_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.component'),
        ),
    ]
