# Generated by Django 5.2.8 on 2026-02-07 15:45

from django.db import migrations, models
from uuid6 import uuid7


def backfill_report_uuids(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    for report in Report.objects.filter(uuid__isnull=True):
        report.uuid = uuid7()
        report.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report_assigned_to_report_status"),
    ]

    operations = [
        # 1️⃣ Add uuid field safely (nullable, no default)
        migrations.AddField(
            model_name="report",
            name="uuid",
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),

        # 2️⃣ Backfill UUIDs row-by-row
        migrations.RunPython(backfill_report_uuids),
    ]