# Generated by Django 5.2.8 on 2026-02-07 15:46

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, unique=True),
        ),
    ]
