# Generated by Django 5.2.8 on 2026-07-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0001_initial'),
        ('reports', '0009_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_via_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to='public_portal.publicreportinglink'),
        ),
    ]
