# Generated by Django 5.2.8 on 2026-07-21 17:32

import uuid6
from django.conf import settings
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    ReportAttachment = apps.get_model('reports', 'ReportAttachment')
    for row in ReportAttachment.objects.all():
        row.uuid = uuid6.uuid7()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_uuid'),
        ('projects', '0011_project_anon_attachments_enabled_and_more'),
        ('public_portal', '0003_merge_0001_initial_0002_create_anon_user'),
        ('reports', '0010_report_is_anonymous_report_submitted_via_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportattachment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reportattachment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='impact',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['project', 'status'], name='reports_rep_project_572f29_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['project', 'created_at'], name='reports_rep_project_f356db_idx'),
        ),
    ]
