# Generated by Django 5.2.8 on 2026-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reportattachment_uuid_alter_report_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='custom_fields_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(db_index=True, default='bug', max_length=50),
        ),
    ]
