# Generated by Django 5.2.8 on 2026-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='parent_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='parent_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
