# Generated by Django 5.2.8 on 2026-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_organisation_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='anon_reporting_enabled',
            field=models.BooleanField(default=True, help_text='Organisation-wide toggle. If False, no project in this org can accept anonymous reports.'),
        ),
    ]
