# Generated by Django 5.2.8 on 2026-01-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('projects', '0003_alter_project_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='projects.project'),
        ),
    ]
