# Generated by Django 5.2.8 on 2026-02-07 15:34

from django.db import migrations, models
from uuid6 import uuid7


def backfill_component_uuids(apps, schema_editor):
    Component = apps.get_model("components", "Component")
    for component in Component.objects.filter(uuid__isnull=True):
        component.uuid = uuid7()
        component.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_alter_component_project"),
    ]

    operations = [
        # 1️⃣ Add uuid field safely (NO default, NO unique)
        migrations.AddField(
            model_name="component",
            name="uuid",
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),

        # 2️⃣ Backfill UUIDs row-by-row
        migrations.RunPython(backfill_component_uuids),
    ]