# Generated by Django 5.2.8 on 2026-02-07 15:36

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, unique=True),
        ),
    ]
