# Generated by Django 5.2.8 on 2026-07-05 10:06

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_alter_organisation_members'),
        ('projects', '0008_project_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('report_assigned', 'Report Assigned'), ('report_reassigned', 'Report Reassigned'), ('report_status_changed', 'Report Status Changed'), ('report_commented', 'New Comment'), ('collaborator_added', 'Added as Collaborator'), ('report_impact_changed', 'Report Impact Changed'), ('invite_collaborator', 'Collaboration Invite'), ('invite_organisation', 'Organisation Invite'), ('invite_project_head', 'Project Head Invite')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_content_type', models.CharField(max_length=100)),
                ('target_uuid', models.UUIDField()),
                ('is_read', models.BooleanField(default=False)),
                ('requires_action', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, unique=True)),
                ('invite_type', models.CharField(choices=[('collaborator', 'Project Collaborator'), ('organisation', 'Organisation Member'), ('project_head', 'Project Head')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organisations.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='notifications.notification')),
            ],
        ),
    ]
