# Generated by Django 5.2.8 on 2026-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_created', 'New Report Created'), ('report_assigned', 'Report Assigned'), ('report_reassigned', 'Report Reassigned'), ('report_status_changed', 'Report Status Changed'), ('report_commented', 'New Comment'), ('collaborator_added', 'Added as Collaborator'), ('report_impact_changed', 'Report Impact Changed'), ('invite_collaborator', 'Collaboration Invite'), ('invite_organisation', 'Organisation Invite'), ('invite_project_head', 'Project Head Invite')], max_length=50),
        ),
    ]
