# Generated by Django 5.2.8 on 2026-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_created', 'New Report Created'), ('report_assigned', 'Report Assigned'), ('report_reassigned', 'Report Reassigned'), ('report_status_changed', 'Report Status Changed'), ('report_commented', 'New Comment'), ('collaborator_added', 'Added as Collaborator'), ('report_impact_changed', 'Report Impact Changed'), ('beta_enrollment', 'Beta Program Enrollment'), ('invite_collaborator', 'Collaboration Invite'), ('invite_organisation', 'Organisation Invite'), ('invite_project_head', 'Project Head Invite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
